### PR TITLE
exposing "path" to QML

### PR DESCRIPTION
**Pull request by tokejepsen**
For https://github.com/pyblish/pyblish-qml/pull/143

### CODE REVIEW

**Comment by mottosso** [comment]
The way pull-requests work, is that they come from a branch of your repository, and they stay up to date with that branch when you make changes to it.

In this case, the two pull-requests are identical. If you want to make multiple pull-requests, you'll need a branch per request. But it's fine in this case I think, to have the two commits in there instead. They are quite minimal and clear in themselves.

**Comment by tokejepsen** [comment]
I see. So you would prefer a branch per issue PR?

**Comment by mottosso** [comment]
For separate, independent pull-requests, such as two completely different features, I'd go for separate branches, such that the pull-requests can be made independently.

But for a collection of commits all relating to a single feature, or only slightly different aspect, a single PR, such as this one, is okay.

**Comment by tokejepsen** [comment]
Cool, will do.

**Pull request merged**
